# Generated by Django 3.0.5 on 2020-07-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscriptions',
            new_name='Emails',
        ),
    ]
